channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyviz
dependencies:
  - pip
  - pytorch=2.0
  - pytorch-cuda=11.7
  - pytorch-lightning=2.0
  - pyinterp
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - xrft
  - metpy
  - scipy
  - matplotlib
  - holoviews
  - pip:
    - GitPython
    - einops
    - hydra-core
    - kornia
    - tabulate
